### ISSUE TITLE
Precio materiales

### ISSUE THREAD

**Issue by jorge-vnarvaez** [jorge-vnarvaez/administracion_elancar#24]
- [x] Se debe crear un componente que liste todos los materiales con los que trabaja Elancar.
- [x] Se debe listar todos los productos que vende Elancar.
- [x] Se debe generar un filtro que interactúe con el componente de materiales
     - [x] Al seleccionar un material se deben mostrar solo los productos que contienen dicho material
- [x] Se debe crear un input que permita ingresar el nuevo precio del material (por kg)
- [x] Al presionar un botón se debe recalcular el precio actual del producto en base a (precio por kg * kg) y actualizar el listado de productos.

**Comment by 1TzYersonzT1** [comment]
- [x] ventana emergente que confirme o cancele la operación de actualizar precio
